name: fok_kometa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

msix_config:
  publisher_display_name: Dumilin Vadim
  display_name: FOK_Kometa
  msix_version: 1.0.0.0
  logo_path: C:\FLUTTER PROJECTS\fok_kometa\lib\theme\images\fok_logo.png

dependencies:
  build_runner:
  calendar_timeline: ^1.1.2
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  fl_chart: ^0.62.0
  flex_color_scheme: ^6.1.2
  flex_seed_scheme: ^1.2.2
  fluent_ui: ^4.5.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: ^3.0.2
  flutter_svg: ^2.0.5
  flutter_time_picker_spinner: ^2.0.0
  flutter_verification_code: ^1.1.6
  glass_kit: ^2.0.1
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  json_annotation: ^4.8.0
  mask_text_input_formatter: ^2.4.0
  material_design_icons_flutter: ^6.0.7096
  persistent_bottom_nav_bar: any
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  smooth_page_indicator: ^1.0.1
  switcher_button: ^0.0.4
  syncfusion_flutter_charts: ^21.2.3
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  # analyzer: ^2.6.0
  # dcdg: ^4.1.0

dev_dependencies:

  build_runner: null

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  msix: ^3.12.2

flutter:

  uses-material-design: true

  assets:
    - lib/theme/images/background/noisable-gradient-1.jpg
    - lib/theme/images/background/noisable-gradient-1-maxsize.jpg
    - lib/theme/images/background/noisable-gradient-1-small.jpg
    - lib/theme/images/background/icons-pic/dumbbell.png
    - lib/theme/images/background/layered-waves-haikei.png
    - lib/theme/images/kometa-map.png
    - lib/theme/images/logo2.png
    - lib/theme/images/logosvg.svg
    - lib/theme/images/background/Rectangle.jpg
    
  # fonts:
  #   - asset: packages/food_icons/Food.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
