@startuml
set namespaceSeparator ::

class "fok_kometa::models::card::card_category_model.dart::CardCategoryModel" {
  +int id_card_category
  +String name
  +int number_of_visits
  +DateTime start_date
  +DateTime end_date
  +int hashCode
  +CardCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::card::card_model.dart::CardModel" {
  +int id_card
  +String name
  +String description
  +int cost
  +int hashCode
  +CardModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::card::client_card_model.dart::ClientCardModel" {
}

class "fok_kometa::models::client_model.dart::ClientModel" {
}

class "fok_kometa::models::diet::diet_category_model.dart::DietCategoryModel" {
  +int id
  +String name
  +int hashCode
  +DietCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::diet::diet_model.dart::DietModel" {
  +int id
  +String name
  +int duration
  +DietCategoryModel diet_category
  +List<EatingModel> eating
  +int hashCode
  +DietModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::diet::diet_model.dart::DietModel" o-- "fok_kometa::models::diet::diet_category_model.dart::DietCategoryModel"

class "fok_kometa::models::diet::dish_model.dart::DishModel" {
  +int id
  +String name
  +String kcal
  +PFCModel pfc
  +int hashCode
  +DishModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::diet::dish_model.dart::DishModel" o-- "fok_kometa::models::diet::pfc_model.dart::PFCModel"

class "fok_kometa::models::diet::eating_model.dart::EatingModel" {
  +int id
  +String name
  +TimeOfDay eating_time
  +List<DishModel> dish
  +int hashCode
  +EatingModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::diet::eating_model.dart::EatingModel" o-- "flutter::src::material::time.dart::TimeOfDay"

class "fok_kometa::models::diet::pfc_model.dart::PFCModel" {
  +int id
  +String proteins
  +String fats
  +String carbohydrates
  +int hashCode
  +PFCModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::group_workout::coach_model.dart::CoachModel" {
  +int id_coach
  +String coachs_second_name
  +String coachs_first_name
  +String coachs_patronymic
  +String specialization
  +int work_experience
  +String sporting_achievements
  +int hashCode
  +CoachModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::group_workout::group_workout_category_model.dart::GroupWorkoutCategoryModel" {
  +int id_group_workout_category
  +String name
  +int hashCode
  +GroupWorkoutCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::group_workout::group_workout_model.dart::GroupWorkoutModel" {
  +int id
  +String name
  +String description
  +String load_score
  +String recommended_age
  +DateTime event_date
  +TimeOfDay start_time
  +TimeOfDay end_time
  +GroupWorkoutCategoryModel group_workout_category
  +CoachModel coach
  +int hashCode
  +GroupWorkoutModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::group_workout::group_workout_model.dart::GroupWorkoutModel" o-- "flutter::src::material::time.dart::TimeOfDay"
"fok_kometa::models::group_workout::group_workout_model.dart::GroupWorkoutModel" o-- "fok_kometa::models::group_workout::group_workout_category_model.dart::GroupWorkoutCategoryModel"
"fok_kometa::models::group_workout::group_workout_model.dart::GroupWorkoutModel" o-- "fok_kometa::models::group_workout::coach_model.dart::CoachModel"        

class "fok_kometa::models::news::news_category_model.dart::NewsCategoryModel" {
  +int id
  +String name
  +int hashCode
  +NewsCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::news::news_model.dart::NewsModel" {
  +int id
  +String title
  +String content
  +DateTime create_date
  +NewsCategoryModel news_category
  +int hashCode
  +NewsModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::news::news_model.dart::NewsModel" o-- "fok_kometa::models::news::news_category_model.dart::NewsCategoryModel"

class "fok_kometa::models::person_workout::exercise_category_model.dart::ExerciseCategoryModel" {
  +int id_exercise_category
  +String name
  +int hashCode
  +ExerciseCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::person_workout::exercise_model.dart::ExerciseModel" {
  +int id_exercise
  +String name
  +String description
  +int load_score
  +List<ExerciseCategoryModel> exercise_category
  +List<ExercisePlanModel> exercise_plan
  +int hashCode
  +ExerciseModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::person_workout::exercise_plan_model.dart::ExercisePlanModel" {
  +int id_exercise_plan
  +String name
  +String description
  +int hashCode
  +ExercisePlanModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::person_workout::person_workout_exercise_model.dart::PersonWorkoutExerciseModel" {
  +ExerciseModel exercise
  +PersonWorkoutModel person_workout
  +int hashCode
  +PersonWorkoutExerciseModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::person_workout::person_workout_exercise_model.dart::PersonWorkoutExerciseModel" o-- "fok_kometa::models::person_workout::exercise_model.dart::ExerciseModel"
"fok_kometa::models::person_workout::person_workout_exercise_model.dart::PersonWorkoutExerciseModel" o-- "fok_kometa::models::person_workout::person_workout_model.dart::PersonWorkoutModel"

class "fok_kometa::models::person_workout::person_workout_model.dart::PersonWorkoutModel" {
  +int id_person_workout
  +String name
  +String description
  +List<ExerciseModel> exercise
  +int hashCode
  +PersonWorkoutModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::service::service_category_model.dart::ServiceCategoryModel" {
  +int id
  +String name
  +int hashCode
  +ServiceCategoryModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "fok_kometa::models::service::service_model.dart::ServiceModel" {
  +int id_service
  +String name
  +int cost
  +String description
  +ServiceCategoryModel service_category
  +int hashCode
  +ServiceModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"fok_kometa::models::service::service_model.dart::ServiceModel" o-- "fok_kometa::models::service::service_category_model.dart::ServiceCategoryModel"

class "fok_kometa::models::user_model.dart::UserModel" {
  +User supa_user
  +Role role
  +int hashCode
  +UserModel copyWith()
  +String toString()
  +bool ==()
}

"fok_kometa::models::user_model.dart::UserModel" o-- "gotrue::src::types::user.dart::User"
"fok_kometa::models::user_model.dart::UserModel" o-- "fok_kometa::models::user_model.dart::Role"

abstract class "fok_kometa::models::user_model.dart::Role" {
  +String name
}

class "fok_kometa::models::user_model.dart::Manager" {
  +String name
}

"fok_kometa::models::user_model.dart::Role" <|-- "fok_kometa::models::user_model.dart::Manager"

class "fok_kometa::models::user_model.dart::Client" {
  +String name
}

"fok_kometa::models::user_model.dart::Role" <|-- "fok_kometa::models::user_model.dart::Client"

class "fok_kometa::service::auth.service.dart::AuthService" {
  {static} -void _subscribeToUserScheme()
  {static} +Future<void> signUp()
  {static} +FutureOr<dynamic> signIn()
}

class "fok_kometa::service::supabase.credentials.dart::SupabaseCredentials" {
  {static} +String API_KEY
  {static} +String API_URL
  {static} +SupabaseClient supabaseClient
}

"fok_kometa::service::supabase.credentials.dart::SupabaseCredentials" o-- "supabase::src::supabase_client.dart::SupabaseClient"

class "fok_kometa::stuffs::graphql.dart::GRaphQLProvider" {
  {static} +GraphQLClient client
}

"fok_kometa::stuffs::graphql.dart::GRaphQLProvider" o-- "graphql::src::graphql_client.dart::GraphQLClient"

class "fok_kometa::stuffs::widgets.dart::NewsPost" {
  +String id_news
  +String title
  +String content
  +String create_date
  +String news_category
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::stuffs::widgets.dart::NewsPost"

class "fok_kometa::stuffs::widgets.dart::GroupWorkoutPost" {
  +String id_group_workout
  +String name
  +String description
  +String load_score
  +String recommended_age
  +String event_date
  +String start_time
  +String end_time
  +String group_workout_category
  +String coach_name
  +String coach_second_name
  +String coach_patronymic
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::stuffs::widgets.dart::GroupWorkoutPost"

class "fok_kometa::stuffs::widgets.dart::ServicePost" {
  +String id_service
  +String name
  +String cost
  +String description
  +String service_category
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::stuffs::widgets.dart::ServicePost"

class "fok_kometa::stuffs::widgets.dart::PersonWorkoutPost" {
  +String id_person_workout
  +String name
  +String description
  +String id_exercise
  +String exercise_name
  +String exercise_description
  +String exercise_load_score
  +String id_exercise_category
  +String exercise_category_name
  +String id_exercise_plan
  +String exercise_plan_name
  +String exercise_plan_description
  +String exercise_plan_number_of_repetitions
  +String exercise_plan_number_of_approaches
  +String exercise_plan_rest_time
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::stuffs::widgets.dart::PersonWorkoutPost"

class "fok_kometa::theme::theme.dart::ThemeNotifier" {
  +String key
  -bool _darkTheme
  +bool darkTheme
  +dynamic toggleTheme()
  -dynamic _initPrefs()
  -dynamic _loadFromPrefs()
  -dynamic _saveToPrefs()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "fok_kometa::theme::theme.dart::ThemeNotifier"

class "fok_kometa::view::login_page.dart::login_page" {
  {static} +String route
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::login_page.dart::login_page"

class "fok_kometa::view::login_page.dart::LoginPage" {
  +State<LoginPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::login_page.dart::LoginPage"

class "fok_kometa::view::login_page.dart::_LoginPageState" {
  +FocusNode loginNode
  +FocusNode passwordNode
  +FocusNode btn_contNode
  +TextEditingController loginController
  +TextEditingController passwordController
  -GlobalKey<FormState> _loginformKey
  -GlobalKey<FormState> _passwordformKey
  -GlobalKey<FormState> _fokformKey
  -String _email
  -String _password
  -bool _isAllExist
  -bool _isPasswordExist
  -bool _isEmailExist
  +bool light0
  +void initState()
  +void dispose()
  +Widget build()
  -void _checkPassword()
  -void _checkEmail()
}

"fok_kometa::view::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"fok_kometa::view::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"fok_kometa::view::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::login_page.dart::_LoginPageState"

class "fok_kometa::view::menu_page.dart::menu_page" {
  {static} +String route
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::menu_page.dart::menu_page"

class "fok_kometa::view::menu_page.dart::Menu" {
  +State<Menu> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::menu_page.dart::Menu"

class "fok_kometa::view::menu_page.dart::_MenuState" {
  +int index
  +List<StatefulWidget> screens
  +StreamSubscription<dynamic>? sub
  +void initState()
  +void dispose()
  +Widget build()
}

"fok_kometa::view::menu_page.dart::_MenuState" o-- "dart::async::StreamSubscription<dynamic>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::menu_page.dart::_MenuState"

class "fok_kometa::view::registration_page.dart::registration_page" {
  {static} +String route
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::registration_page.dart::registration_page"

class "fok_kometa::view::registration_page.dart::Registration" {
  +State<Registration> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::registration_page.dart::Registration"

class "fok_kometa::view::registration_page.dart::_RegistrationState" {
  +FocusNode loginNode
  +FocusNode passwordNode
  +FocusNode btn_contNode
  +TextEditingController loginController
  +TextEditingController passwordController
  -GlobalKey<FormState> _loginformKey
  -GlobalKey<FormState> _passwordformKey
  -GlobalKey<FormState> _fokformKey
  -String _password
  -double _strength
  +RegExp numReg
  +RegExp letterReg
  -String _displayText
  +void initState()
  +void dispose()
  +Widget build()
  -void _checkPassword()
}

"fok_kometa::view::registration_page.dart::_RegistrationState" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"fok_kometa::view::registration_page.dart::_RegistrationState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"fok_kometa::view::registration_page.dart::_RegistrationState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::registration_page.dart::_RegistrationState"

class "fok_kometa::view::screens::1_first_page.dart::first_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::1_first_page.dart::first_page"

class "fok_kometa::view::screens::1_first_page.dart::FirstPage" {
  +HasuraConnect hasuraConnect
  +State<FirstPage> createState()
}

"fok_kometa::view::screens::1_first_page.dart::FirstPage" o-- "hasura_connect::src::presenter::hasura_connect_base.dart::HasuraConnect"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::1_first_page.dart::FirstPage"

class "fok_kometa::view::screens::1_first_page.dart::_FirstPageState" {
  +QueryOptions<Object?> currentQuery
  +List<NewsModel> news
  +dynamic newsUn
  +bool isLoading
  +void initState()
  +Widget build()
}

"fok_kometa::view::screens::1_first_page.dart::_FirstPageState" o-- "graphql::src::core::query_options.dart::QueryOptions<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::1_first_page.dart::_FirstPageState"

class "fok_kometa::view::screens::2_schedule_page.dart::schedule_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::2_schedule_page.dart::schedule_page"

class "fok_kometa::view::screens::2_schedule_page.dart::SchedulePage" {
  +State<SchedulePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::2_schedule_page.dart::SchedulePage"

class "fok_kometa::view::screens::2_schedule_page.dart::_SchedulePageState" {
  -PageController _controller
  +String textdate
  +List<GroupWorkoutModel> groupWorkouts
  +dynamic groupWorkoutsUn
  +QueryOptions<Object?> currentQuery
  +DateTime todaydate
  +DateTime tomorrowdate
  +DateTime aftertomorrowdate
  +bool isLoading
  +void initState()
  +Widget build()
}

"fok_kometa::view::screens::2_schedule_page.dart::_SchedulePageState" o-- "flutter::src::widgets::page_view.dart::PageController"
"fok_kometa::view::screens::2_schedule_page.dart::_SchedulePageState" o-- "graphql::src::core::query_options.dart::QueryOptions<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::2_schedule_page.dart::_SchedulePageState"

class "fok_kometa::view::screens::3_services_page.dart::services_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::3_services_page.dart::services_page"

class "fok_kometa::view::screens::3_services_page.dart::ServicesPage" {
  +State<ServicesPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::3_services_page.dart::ServicesPage"

class "fok_kometa::view::screens::3_services_page.dart::_ServicesPageState" {
  +QueryOptions<Object?> currentQuery
  +List<ServiceModel> services
  +dynamic serviceUn
  +bool isLoading
  +void initState()
  +Widget build()
}

"fok_kometa::view::screens::3_services_page.dart::_ServicesPageState" o-- "graphql::src::core::query_options.dart::QueryOptions<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::3_services_page.dart::_ServicesPageState"

class "fok_kometa::view::screens::4_workout_page.dart::workout_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::4_workout_page.dart::workout_page"

class "fok_kometa::view::screens::4_workout_page.dart::WorkoutPage" {
  +HasuraConnect hasuraConnect
  +State<WorkoutPage> createState()
}

"fok_kometa::view::screens::4_workout_page.dart::WorkoutPage" o-- "hasura_connect::src::presenter::hasura_connect_base.dart::HasuraConnect"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::4_workout_page.dart::WorkoutPage"

class "fok_kometa::view::screens::4_workout_page.dart::_WorkoutPageState" {
  +QueryOptions<Object?> currentQuery
  +List<PersonWorkoutModel> personWorkoutss
  +dynamic personWorkoutUn
  +bool isLoading
  +void initState()
  +Widget build()
}

"fok_kometa::view::screens::4_workout_page.dart::_WorkoutPageState" o-- "graphql::src::core::query_options.dart::QueryOptions<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::4_workout_page.dart::_WorkoutPageState"

class "fok_kometa::view::screens::5_profile_page.dart::profile_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::5_profile_page.dart::profile_page"

class "fok_kometa::view::screens::5_profile_page.dart::ProfilePage" {
  +BuildContext? parentNavigatorContext
  +State<ProfilePage> createState()
}

"fok_kometa::view::screens::5_profile_page.dart::ProfilePage" o-- "flutter::src::widgets::framework.dart::BuildContext"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::5_profile_page.dart::ProfilePage"

class "fok_kometa::view::screens::5_profile_page.dart::_ProfilePageState" {
  +User supaUser
  +Map<dynamic, dynamic>? thisUser
  +void initState()
  +Widget build()
}

"fok_kometa::view::screens::5_profile_page.dart::_ProfilePageState" o-- "gotrue::src::types::user.dart::User"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::5_profile_page.dart::_ProfilePageState"

class "fok_kometa::view::screens::screens_profile::calculators_page.dart::CalculatorsPage" {
  +State<CalculatorsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::calculators_page.dart::CalculatorsPage"

class "fok_kometa::view::screens::screens_profile::calculators_page.dart::_CalculatorsPageState" {
  -TextEditingController _weightController
  -TextEditingController _heightController
  +double bmi
  -TextEditingController _weightController2
  -int _activityLevel
  -double _dailyWaterIntake
  +void dispose()
  +void calculateBmi()
  +void clearBmi()
  +void calculateDailyWaterIntake()
  +void clearDailyWaterIntake()
  +Widget build()
}

"fok_kometa::view::screens::screens_profile::calculators_page.dart::_CalculatorsPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::calculators_page.dart::_CalculatorsPageState"

class "fok_kometa::view::screens::screens_profile::diets_page.dart::DietsPage" {
  +State<DietsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::diets_page.dart::DietsPage"

class "fok_kometa::view::screens::screens_profile::diets_page.dart::_DietsPageState" {
  +List<DietModel> diets
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::diets_page.dart::_DietsPageState"

class "fok_kometa::view::screens::screens_profile::feedback_page.dart::feedback_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::screens_profile::feedback_page.dart::feedback_page"

class "fok_kometa::view::screens::screens_profile::feedback_page.dart::FeedbackPage" {
  +State<FeedbackPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::feedback_page.dart::FeedbackPage"

class "fok_kometa::view::screens::screens_profile::feedback_page.dart::_FeedbackPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::feedback_page.dart::_FeedbackPageState"

class "fok_kometa::view::screens::screens_profile::options_page.dart::options_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::screens_profile::options_page.dart::options_page"

class "fok_kometa::view::screens::screens_profile::options_page.dart::OptionsPage" {
  +State<OptionsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::options_page.dart::OptionsPage"

class "fok_kometa::view::screens::screens_profile::options_page.dart::_OptionsPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::options_page.dart::_OptionsPageState"

class "fok_kometa::view::screens::screens_profile::personal_data_page.dart::personal_data_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::screens_profile::personal_data_page.dart::personal_data_page"       

class "fok_kometa::view::screens::screens_profile::personal_data_page.dart::PersonalDataPage" {
  +State<PersonalDataPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::personal_data_page.dart::PersonalDataPage"

class "fok_kometa::view::screens::screens_profile::personal_data_page.dart::_PersonalDataPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::personal_data_page.dart::_PersonalDataPageState"

class "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::about_app_page" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::about_app_page"

class "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::AboutAppPage" {
  +State<AboutAppPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::AboutAppPage" 

class "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::_AboutAppPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "fok_kometa::view::screens::screens_profile::screens_options::about_app_page.dart::_AboutAppPageState"    


@enduml